### DISCUSSION TITLE
Decorative part title page.

### DISCUSSION THREAD

**Discussion by no-vici** [Omikhleia/resilient.sile#67] [Q&A] [answered]
Hi typographers,

I would like to have a part title page that looks similar to the below screenshot.

![swappy-20230929_154324](https://github.com/Omikhleia/resilient.sile/assets/113570767/ee007e5d-3d7b-4cc0-82a5-0684c91a5e28)

Would it this be possible in resilient style module in the future? Some thing like this would be nice:

```
sectioning-part:
  inherit: "sectioning-base"
  origin: "resilient.book"
  style:
    font:
      size: "3em"
      weight: 500
    paragraph:
      after:
        skip: "bigskip"
      align: "right"
      before:
        skip: "25%fh"
        img: /path/to/image
        img-size: "25%fw"
        img-align: left

```
