### ISSUE TITLE
`before` and `after` skips in styles aren't working for tables.

### ISSUE THREAD

**Issue by jodros** [Omikhleia/resilient.sile#103]
When I change these options in `figure` they've effect, but nothing when it comes to tables...

```yml
table:
  origin: "resilient.book"
  style:
    paragraph:
      after:
        skip: "3%fh"
      align: "center"
      before:
        indent: false
        skip: "3%fh"
```

**Comment by Omikhleia** [comment]
@jodros I quickly hacked markdown.sile to always wrap tables into a captioned-table (and the latter is responsible for handling a caption if present) and check what would happen.

With the following style (just to check some skips):

```
table:
  origin: "resilient.book"
  style:
    paragraph:
      after:
        skip: "1cm"
      align: "center"
      before:
        indent: false
        skip: "0.5cm"
```

Running in debug `sile -c resilient.book -u inputters.markdown temp/tab.dj -d resilient.styles` (the latter is verbose but notably shows the styling skips, merged/collapsed by the consecutive skip logic) on a test file with two tables (one with caption, the other without):

![image](https://github.com/user-attachments/assets/b3c05fbe-f90b-428d-b9b3-8d3ed844d5af)

Note however that **ptable** inserts its own (non-collapsing) small skips (I'm afraid it's yet another hornets' nest...). 
Yet, would that meet expectations better?
If so, I can push the change to markdown.sile, which will have a new release soon...
