### ISSUE TITLE
Styles do not allow not showing captioned element numbers

### ISSUE THREAD

**Issue by Omikhleia** [Omikhleia/resilient.sile#21]
From discussion https://github.com/Omikhleia/markdown.sile/discussions/34#discussioncomment-5345797

There are two different ways at looking at this topic:
- Disabling numbering, e.g. with `numbering=false` in SIL or `.unnumbered` in Markdown (https://github.com/Omikhleia/markdown.sile/issues/51)
- Having styles that do not show the number, even if internally present...

Regarding the second point, in the above-mentioned discussion, I wrote:

> styles currently don't address it

But it's kind of an overlooked topic or a loophole in the logic:

https://github.com/Omikhleia/resilient.sile/blob/d25cc412ba3e798721d8d5cd86d836b0fbb0157f/packages/resilient/sectioning/init.lua#L118-L128

That "else" seems bad :)
When the sectioning style has no `numberstyle.main` entry, we issue a warning, and still display an "unstyled" number. Perhaps we should just accept it and not show anything there. It would need proper documentation --

With (default) style such as:

```
figure-caption:
...
    sectioning:
      counter:
        id: "figures"
        level: 1
      numberstyle:
        main: "figure-caption-main-number"
        reference: "figure-caption-ref-number"
      ...
```

One gets the number displayed with the said `figure-caption-main-number` numbering style....

But if the `main` field is removed from the definition, rather than warn and do something, we could just skip the number output...

**Comment by no-vici** [comment]
Can something like:

```
figure-caption-main-number:
  inherit: "figure-caption-base-number"
  origin: "resilient.book"
  style:
    font:
      features: "+smcp"
    numbering:
      display: true|false
      after:
        kern: "iwsp"
        text: "."
      before:
        text: "Hình "

```
And could `if secStyle.numberstyle.main.display then` implemented?
