### ISSUE TITLE
Alternative way to disable (figure caption etc) numbering

### ISSUE THREAD

**Issue by Omikhleia** [Omikhleia/resilient.sile#24]
Split from discussion in https://github.com/Omikhleia/resilient.sile/issues/21#issuecomment-1474685375 

Can something like this be implemented:

```
figure-caption-main-number:
  inherit: "figure-caption-base-number"
  style:
    ...
    numbering:
      visible: true|false
     ...
```

Check the whole discussion on the referred issue.
