### ISSUE TITLE
Default folio style introduces a paragraph indent on even pages

### ISSUE THREAD

**Issue by Omikhleia** [Omikhleia/resilient.sile#30]
Oops.

An unnoticed side effect of having switched from SILE's ragged environments to our own via paragraph styling in 3a16ef1f96949fe7460ce004d347972ceef67f51
The former don't support nesting, but cancel parindent; the latter support (r/l skip) nesting but doesn't touch the parindent (by design, on purpose!)... And see details further below.

![image](https://user-images.githubusercontent.com/18075640/230808938-741ee17a-b2e8-4f2a-bdd1-090e03a1b8ec.png)

Workaround:

Override the default style in the document's style file:

```yaml
folio-even:
  inherit: "folio-base"
  origin: "resilient.book"
  style:
    paragraph:
      align: "left"
      before:
        indent: false

folio-odd:
  inherit: "folio-base"
  origin: "resilient.book"
  style:
    paragraph:
      align: "right"
      before:
        indent: false
```

Note
- If we generalize the above, §3.1 in the manual might need an update too
- another solution would be to fully cancel the parindent in folios generically, which I thought we did with a `SILE.call("noindent")`, but paragraph styles re-enable it currently (= the default is true)

There might be more than meets the eye, here (wrong default?), to check.

EDIT: And we also have to check how SILE issue 1699 gets addressed, because we are also in that situation (temporary environment), with parindent scoping issues.
